# This file was generated by GoReleaser. DO NOT EDIT.
cask "jalapeno" do
  desc "Jalapeno is a CLI for creating, managing and sharing spiced up project templates"
  homepage "https://futurice.github.io/jalapeno/"
  version "1.16.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jalapeno"

  on_macos do
    on_intel do
      url "https://github.com/futurice/jalapeno/releases/download/v1.16.2/jalapeno-darwin-amd64.tar.gz"
      sha256 "d217277a65517e7ebc094d256728dfb6857f12aa9237be71e694df1891d05ccc"
    end
    on_arm do
      url "https://github.com/futurice/jalapeno/releases/download/v1.16.2/jalapeno-darwin-arm64.tar.gz"
      sha256 "eb7f0e49af7db55a1a0cfa78eb79379f87bc6bc2605f285c3cdea8f20c3ed07f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/futurice/jalapeno/releases/download/v1.16.2/jalapeno-linux-amd64.tar.gz"
      sha256 "e6abbe8de4e2fad5187be6d530db35385485a6c1757355be9e25a8b8ec01fb26"
    end
    on_arm do
      url "https://github.com/futurice/jalapeno/releases/download/v1.16.2/jalapeno-linux-arm64.tar.gz"
      sha256 "f343056ef9cb7de00beab5b315e3e774bac08e18417e20dcb1ea9f61d4ea3859"
    end
  end

  conflicts_with formula: [
      "jalapeno",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jalapeno"]
    end
  end

  # No zap stanza required
end
