# This file was generated by GoReleaser. DO NOT EDIT.
cask "jalapeno" do
  desc "Jalapeno is a CLI for creating, managing and sharing spiced up project templates"
  homepage "https://futurice.github.io/jalapeno/"
  version "1.17.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jalapeno"

  on_macos do
    on_intel do
      url "https://github.com/futurice/jalapeno/releases/download/v1.17.0/jalapeno-darwin-amd64.tar.gz"
      sha256 "d3362a8d6551831f967bad571ea07fd03cdbdce7a41e102b537f969f63cf0532"
    end
    on_arm do
      url "https://github.com/futurice/jalapeno/releases/download/v1.17.0/jalapeno-darwin-arm64.tar.gz"
      sha256 "8eb68b78e1318da8be6b8048bd5a34cb39134c51d3c0e898e397139bd2b4be28"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/futurice/jalapeno/releases/download/v1.17.0/jalapeno-linux-amd64.tar.gz"
      sha256 "664aff9a1b6758fbcc2218da102bd5a4ed373c945051b802dcab5e1e6b581a76"
    end
    on_arm do
      url "https://github.com/futurice/jalapeno/releases/download/v1.17.0/jalapeno-linux-arm64.tar.gz"
      sha256 "df21222019b071215fad7744b83552ca7938c99bcba94a506e4c6661544bec0c"
    end
  end

  conflicts_with formula: [
      "jalapeno",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jalapeno"]
    end
  end

  # No zap stanza required
end
